### ISSUE TITLE
2080ti run demopy   :cuda runtime error(11)

### ISSUE THREAD

**Issue by xujin1184104394** [NVIDIA/FastPhotoStyle#71]
environment:
CUDA10
CUDNN 7.4.2
Pytorch 1.0.1
GPU 2080ti
Run python demo.py to report an error:

python demo.py --output_image_path results/example1.png
Resize image: (803,538)->(803,538)
Resize image: (960,540)->(960,540)
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument
Elapsed time in stylization: 0.300527
Traceback (most recent call last):
  File "demo.py", line 47, in <module>
    no_post=args.no_post
  File "/home1/code/FastPhotoStyle/process_stylization.py", line 122, in stylization
    stylized_img = stylization_module.transform(cont_img, styl_img, cont_seg, styl_seg)
  File "/home1/code/FastPhotoStyle/photo_wct.py", line 52, in transform
    csF1 = self.__feature_wct(cF1, sF1, cont_seg, styl_seg)
  File "/home1/code/FastPhotoStyle/photo_wct.py", line 77, in __feature_wct
    target_feature = self.__wct_core(cont_feat_view, styl_feat_view)
  File "/home1/code/FastPhotoStyle/photo_wct.py", line 140, in __wct_core
    if c_e[i] >= 0.00001:
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/generated/../THCTensorMathCompare.cuh:82

**Comment by leijuzi** [comment]
i meet the same issue are you solve it now?

**Comment by xujin1184104394** [comment]
No

**Comment by jbohnslav** [comment]
I had a similar issue on my new RTX GPU. Running on the 1080Ti was fine, and I got a bug in THC with the RTX. I installed PyTorch from source (Ubuntu 18.04), which solved my issue.

**Comment by zrongcheng** [comment]
Please use the cuda 10.0.
