### ISSUE TITLE
Does the code work for CUDA-8.0?

### ISSUE THREAD

**Issue by wanghxcis** [NVIDIA/FastPhotoStyle#8]
Traceback (most recent call last):
  File "demo.py", line 75, in <module>
    out_img = smooth_filter(output_image_path, content_image_path, f_radius=15, f_edge=1e-1)
  File "/home/whx/ml/FastPhotoStyle/smooth_filter.py", line 392, in smooth_filter
    best_ = smooth_local_affine(output_, input_, 1e-7, 3, H, W, f_radius, f_edge)
  File "/home/whx/ml/FastPhotoStyle/smooth_filter.py", line 336, in smooth_local_affine
    m.load(bytes(ptx.encode()))
  File "cupy/cuda/function.pyx", line 175, in cupy.cuda.function.Module.load
  File "cupy/cuda/function.pyx", line 176, in cupy.cuda.function.Module.load
  File "cupy/cuda/driver.pyx", line 141, in cupy.cuda.driver.moduleLoadData
  File "cupy/cuda/driver.pyx", line 72, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_CONTEXT_IS_DESTROYED: context is destroyed

**Comment by Yijunmaverick** [comment]
@wanghxcis Thanks for your interests. 

It should work. See if you have modified the cuda path on Line 334 in _smooth_filter.py_.

**Comment by wanghxcis** [comment]
Thanks for you reply.  I already changed the header file location, but still got the error. Than I updated the nvidia driver from 381 to 390, and update cuda from 8.0 to 9.1, and it works fine.
